### ISSUE TITLE
Where is the Markdown reference?

### ISSUE THREAD

**Issue by rauschma** [slideshow-s9/slideshow-s9.github.io#1]
The [site](slideshow-s9.github.io/) mentions a Markdown reference, but I couldn’t find a link to it.

It may make sense to give the following collection of links more structure (e.g. a bullet list).

>  Home | 10-Minute Quick Start Guide | Command Line Reference | Settings, Tips, Tricks and More | Plugins, Helpers | Syntax Highlighting | Template Pack Gallery | Gradient Themes | Settings Reference | Template Repos | Template Reference | What's New? · Forum (Questions? Comments?) | Tools & Code Repos

Thanks!

**Comment by geraldb** [comment]
Slide Show (S9) uses kramdown like jekyll / github pages, see https://kramdown.gettalong.org/quickref.html Cheers. PS: Thanks for trying. Greetings from Vienna.

PPS: Good points - sorry the docu is outdated - will get reworked in a book edition.

**Comment by rauschma** [comment]
Thanks! I’m particularly curious how to achieve the relatively simple default layouts provided by Keynote (esp. 50% image and 100% image). These cover all of my use cases. Something similar could work well as a visual guide to S9 (icon pointing to piece of Markdown code).

<img width="243" alt="keynote-layouts" src="https://cloud.githubusercontent.com/assets/526114/25151131/aa4c4de8-2484-11e7-9d51-86ee1db1e331.png">

Did you take a look at [Deckset](https://www.decksetapp.com/)? I like some of their syntactic choices for Markdown.

Gruß zurück aus München!

**Comment by geraldb** [comment]
Thanks for the detailed layouts and not yet giving up on slide show (s9).

If I dare to say it's all super simple and easy ;-) - a slide is just a web page or div block or section block and to create your desired slide types all you need is - surprise, surprise - some CSS magic. See <https://webslides.tv> to get inspired (includes a apple keynote remake among other samples).

Tip: To assign a css class to your slide you have some options with slide show (s9):

option 1)  use inline html comments (directives eg.) same as in deckset I think (slide show was first ;-) it's about a 10 year old script/gem)

      or

option 2)  use a bang directive e.g.

    !SLIDE yourstylehere

option 3) use a ruby macro ;-)  

    def pic100
        "" 
    end

and in your slide use

     %pic100

About Deckset - looks great and as you said some shortcuts are nice incl. the auto-scaling of text - but as far as I know it's kind of a closed system - e.g. you cannot tweak or design your own themes (why not? it's just html & css) and not sure what markdown engine (and extensions) get used and so on.

If you do not want to design your own theme - maybe shower.js might be an option (w/ many built-in slide styles/types) -> <http://slideshow-templates.github.io/slideshow-shower/test.material.html>  

Prost nach München.   

PS: The big (new) selling point of slide show (s9) templates is that it's just a jekyll / github pages theme; see <https://github.com/henrythemes/jekyll-talks-theme> as an example.
